In [1]:
import tensorflow as tf

print(tf.__version__)


2.5.0


In [2]:
mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()

In [3]:
import numpy as np
np.set_printoptions(linewidth=200)
import matplotlib.pyplot as plt
print(training_labels[0])
print(training_images[0])

plt.imshow(training_images[0])


9
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0  13  73   0   0   1   4   0   0   0   0   1   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3   0  36 136 127  62  54   0   0   0   1   3   4   0   0   3]
 [  0   0   0   0   0   0   0   0   0   0   0   0   6   0 102 204 176 134 144 123  23   0   0   0   0  12  10   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0 155 236 207 178 107 156 161 109  64  23  77 130  72  15]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0  69 207 223 218 216 216 163 127 121 122 146 141  88 172  66]
 [  0   0   0   0   0   0   0   0   0   1   1   1   0 200 232 232 233 229 223 

In [4]:
class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if(logs.get('accuracy')>0.95):
            print("\nReached 95% accuracy so cancelling training!")
            self.model.stop_training = True


In [5]:
training_images  = training_images / 255.0
test_images = test_images / 255.0

In [6]:
callbacks = myCallback()

model = tf.keras.models.Sequential([tf.keras.layers.Flatten(), 
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu), 
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)])

In [7]:
model.compile(optimizer = tf.optimizers.Adam(),
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=100,callbacks=[callbacks])

Epoch 1/100
1875/1875 [==============================] - 2s 745us/step - loss: 0.5001 - accuracy: 0.8239
Epoch 2/100
1875/1875 [==============================] - 1s 697us/step - loss: 0.3777 - accuracy: 0.8637
Epoch 3/100
1875/1875 [==============================] - 1s 710us/step - loss: 0.3413 - accuracy: 0.8754
Epoch 4/100
1875/1875 [==============================] - 1s 704us/step - loss: 0.3147 - accuracy: 0.8849
Epoch 5/100
1875/1875 [==============================] - 1s 702us/step - loss: 0.2976 - accuracy: 0.8906
Epoch 6/100
1875/1875 [==============================] - 1s 700us/step - loss: 0.2830 - accuracy: 0.8955
Epoch 7/100
1875/1875 [==============================] - 1s 740us/step - loss: 0.2696 - accuracy: 0.8999
Epoch 8/100
1875/1875 [==============================] - 1s 752us/step - loss: 0.2577 - accuracy: 0.9046
Epoch 9/100
1875/1875 [==============================] - 1s 779us/step - loss: 0.2476 - accuracy: 0.9078
Epoch 10/100
1875/1875 [==============================]

In [8]:
model.evaluate(test_images, test_labels)


313/313 [==============================] - 0s 728us/step - loss: 0.4175 - accuracy: 0.8890


[0.41753846406936646, 0.8889999985694885]